In [1]:
import tensorflow as tf

In [2]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])

print(텐서+텐서2)
# 기본 텐서 만들기 그냥 숫자, 리스트 담는곳..
# 텐서를 이용한 한번에 계산하기 스킬 
텐서3 = tf.constant([[1,2],
                     [3,4]])
# 텐서로 행렬 표현하기 
print(tf.add(텐서,텐서2))
# 파이썬의 +*-/를 써도되지만 .add이런 함수를 써도 됨. 
# tf.add()
# tf.subtract()
# tf.divide()
# tf.multiply()
# tf.matmul() 이건 행렬의 곱셈 .. element 끼리 곱이아니라 dot product 
텐서4 = tf.zeros(10) # 이건 0으로 가득찬 텐서를 하나 만들어줌 tf.zeros()
print(텐서4)
텐서5=tf.zeros([2,2])
print(텐서5)
텐서6=tf.zeros([2,2,3]) # 3개의 데이터를 담은 리스트를 하나 생성하고 그걸 두개, 또 두개세트로생성
print(텐서6)
# 차원,디멘션,쉐입이라고 표현함 
print(텐서.shape) # (3,) 자료가 3개 들어잇다 
print(텐서3.shape) # (2, 2) 2행2열의 데이터 
텐서7=tf.constant([[1,2,3],
                     [3,4,5]])
print(텐서7.shape) # 3개의 데이터가 2개 뒤부터 해석하면댐 

print(텐서) 
#tensor의 datatype
# - 정수는 int 
# - 실수는 float 대부분 실수를 이용. 
# 뒤에 데이터타입을 지정해줄수도있음 . ex) tf.constant([2,3,4],tf.float32)
# tf.cast() 이것도 데이터타입 변경할수있따 
w = tf.Variable(1.0) # 변수라는뜻인데 딥러닝에선 weight라고 생각하면됨.
print(w) # 항상 변경이 쉽게쉽게됨.
print(w.numpy) #variable의 값을 불러오고 싶으면 .numpy하면됨
w.assign(2) # 변수만들고 수정하는법 
print(w) #변수에 행렬도 넣을수있음. 

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
(3,)
(2, 2)
(2, 3)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [3]:
# 텐서가 필요한 이유 
# - 행렬로 인풋/w값 저장 가능 
# - 그럼 node값 계산식 쉬워짐 
# ex) 
# 딥러닝을 할 때 인풋이 세개가 있다고치면 웨이트도 세개 
# 곱해서 새로운 노드를 만들고싶음.. (흔한 뉴럴네트워크)
# x1 x2 x3
# w1 w2 w3 = x1w1+x2w2+x3w3
# 이걸 코드로 짜려면 복잡하고 귀찮아서 수학자들이 고안해낸 행렬이라는 개념을 빌려와서
# 노드를 계산할때 많이 씀. .
# 행렬을 쓰면 숫자여러개를 한번에 계산할수있음.. 매우편함 


In [4]:
# # 텐서플로우에선 딥러닝이 어떻게 이루어지나?
# # 딥러닝으로 간단한 수학문제 풀어보기
# # 문제 키와 신발사이즈는 어떤 관련이 있을까요 ?
# 키 = [170,180,175,160]
# 신발 = [260,270,265,255]
# # ??? = a 170 +b  직선의 방정식.. 키를알면 신발사이즈를 알수있음

키 = 170
신발 = 260 

# 신발 = 키 * a + b  키랑 신발이 뭔가연관이 되어있을거같은데 미지수를 곱해서 예측함

a = tf.Variable(0.1)
b = tf.Variable(0.2) 

# def 손실함수():
#     return tf.square손실값(실제값 - 예측값)  :^2이렇게 하진않고 tf.square하면댐

def 손실함수():
    예측값 = 키 *a+b
    return tf.square(260 - 예측값)

opt = tf.keras.optimizers.Adam(learning_rate=0.1) # 경사하강법을 이용해서 w변수들을 업데이트해주는 고마운 친구 
# gradient를 알아서 스마트하게 바꿔줌 Adam..  learning_rate지정도 가능
# opt.minimize(손실함수,var_list=[a,b]) #경사하강법으로 업데이트할 weight Variable목록
# ↑ 경사하강 1번해줌 == a,b를 1번 수정해줌 a와b의값이 0.1, 0.2였었는데 실제답과 유사한 a,b값으로 변한다는뜻.
# 한번만 하면 제대로 예측하는값이 나오지않음.. 그래서 여러번 반복하면됨. 최적값이 나올때까지 

for i in range(300):
    opt.minimize(손실함수,var_list=[a,b])
    print(a.numpy(),b.numpy()) # 보기쉽게 넘파이 
    
# 예측한 신발사이즈 = 키*1.52+1.62 
print(키*1.52+1.62) 

# 우리가만든 linear regression 모델임. 이제 키만 알면 신발사이즈를 추정할 수 있는것.


0.20000002 0.3
0.299743 0.399743
0.39902854 0.49902856
0.4976288 0.59762883
0.5952905 0.6952905
0.69173086 0.7917309
0.78663594 0.88663596
0.8796619 0.9796619
0.9704343 1.0704342
1.0585508 1.1585507
1.1435848 1.2435848
1.2250917 1.3250916
1.3026174 1.4026173
1.3757098 1.4757097
1.4439315 1.5439314
1.5068752 1.6068751
1.5641792 1.6641791
1.615542 1.715542
1.6607362 1.7607361
1.6996179 1.7996178
1.7321334 1.8321333
1.7583209 1.8583208
1.7783084 1.8783083
1.7923075 1.8923074
1.800605 1.900605
1.803553 1.9035529
1.8015567 1.9015566
1.7950644 1.8950644
1.7845562 1.884556
1.7705342 1.8705341
1.7535139 1.8535138
1.7340164 1.8340163
1.7125608 1.8125607
1.689658 1.789658
1.6658051 1.765805
1.6414793 1.7414792
1.6171328 1.7171327
1.5931883 1.6931882
1.5700338 1.6700337
1.5480187 1.6480186
1.5274498 1.6274498
1.5085886 1.6085885
1.4916484 1.5916483
1.4767939 1.5767938
1.4641396 1.5641395
1.453751 1.5537509
1.445646 1.545646
1.4397974 1.5397973
1.4361359 1.5361358
1.4345546 1.5345545
1.4349129 1.5

In [6]:
# 대학 합격 예측 AI 만들기 
# 붙을까요 ?X 붙을확률구하기 O
import pandas as pd
import numpy as np
data = pd.read_csv('./gpascore.csv')
# 데이터 전처리 해야함. nan값에 평균값을 넣거나 행을 삭제하거나 
data.dropna()

y데이터 = data['admit'].values # y입력값 만들기 ..걍 리스트로 다 출력해줌.
x데이터 = []

for i, rows in data.iterrows(): #data라는 데이터프레임을 가로한줄씩 출력해라.. 
    x데이터.append([rows['gre'],rows['gpa'],rows['rank']])
# 근데 .. 파이썬 리스트를 그대로 집어 넣을 순 없음.. 그래서 numpy array 나 tensor를 넣어야함.



model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64,activation='relu'), # 노드의 갯수
    tf.keras.layers.Dense(128,activation='relu'), # 히든레이어의 갯수 결과가 잘 나올때까지 실험으로 파악해야함. 근데 2의제곱으로 많이 표현함 
    tf.keras.layers.Dense(1, activation='sigmoid'), # 마지막출력레이어는 1개만 와야하지 않겠뉘.. 0과1로 나타나니까 .. 근데 여러가지로 예측하려면 마지막 레이어를 신경써서 만들면됨.(확률한개를 예측할때도 1개)
]) #<= 딥러닝 모델 만드는법

# 레이어를 디자인할때 activation function 이 꼭 필요함.
# 마지막 레이어는 예측결과를 뱉어야함 . 0~1사이의 확률로 (0~1사이의 확률을 뱉고싶으면 sigmoid)
# 마지막 출력결과가 0.9 =입학확률 90%

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# optimizer 경사하강법으로 수정함.. 기울기를 뺄때 lerning rate 곱해서 빼준다했는데 optimizer는 그 값을 알맞게 조정해줌. 
# loss function은 확률을 구하고싶을때 binary_crossentropy <- 결과가 0과1사이의 분류/확률문제에서 씀.. 
# metrics는 모델평가할때 모쓸지 

model.fit(np.array(x데이터),np.array(y데이터),epochs=10) #학습시키기 , epochs 몇번 학습을 시킬까

# [[380,3.21,3],[660,3.67,3]] x데이터 이런식으로 만들어야함
# [0,1,1,0...] y라벨 위로가서 pandas부터 

# 예측 
model.predict([[750,3.70,3],[400,2.2,1]]) # 예측은 model.predict(테스트해볼x데이터)

# 1.모델만들기
# 2.데이터집어넣고 학습
# 3.새로운 데이터 예측
# +데이터 전처리
# +모델 튜닝 
# 딥러닝 학습은 연구과정임.. => 실험이 매우 중요 

Epoch 1/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5047
Epoch 2/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 3/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 4/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 5/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 6/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 7/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 8/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 9/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 10/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 11/1000
14/14 [========

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 85/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 86/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 87/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 88/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 89/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 90/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 91/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 92/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 93/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 94/1000
14/14 [=============

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 168/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 169/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 170/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 171/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 172/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 173/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 174/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 175/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 176/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 177/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 250/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 251/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 252/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 253/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 254/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 255/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 256/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 257/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 258/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 259/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 332/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 333/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 334/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 335/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 336/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 337/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 338/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 339/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 340/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 341/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 414/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 415/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 416/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 417/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 418/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 419/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 420/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 421/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 422/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 423/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 496/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 497/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 498/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 499/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 500/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 501/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 502/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 503/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 504/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 505/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 578/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 579/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 580/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 581/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 582/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 583/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 584/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 585/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 586/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 587/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 660/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 661/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 662/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 663/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 664/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 665/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 666/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 667/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 668/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 669/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 742/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 743/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 744/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 745/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 746/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 747/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 748/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 749/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 750/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 751/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 824/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 825/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 826/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 827/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 828/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 829/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 830/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 831/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 832/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 833/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 906/1000
14/14 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5258
Epoch 907/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 908/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 909/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 910/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 911/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 912/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 913/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 914/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 915/1000
14/14 [===

14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 988/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 989/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 990/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 991/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 992/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 993/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 994/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 995/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 996/1000
14/14 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.5258
Epoch 997/1000
14/14 [===